# Generated by Django 2.2.5 on 2022-07-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear_regression', '0003_nodedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField()),
                ('correct_count', models.IntegerField()),
                ('total_count', models.IntegerField()),
            ],
        ),
    ]
